import TasksDetail from '../Tasks/TasksDetail'

const Task = () => {
    return (
        <div className='container'>
            <div className='row'>
                <div className='col-lg-6 col-md-6 col-sm-12 col-xs-12'>
                    <TasksDetail />
                </div>
                <div className='col-lg-6 col-md-6 col-sm-12 col-xs-12'>
                    <h2 className='h5 mb-3 mt-3'>Features</h2>

                    <div className='small'>
                        <p>
                            The edit icon changes state on click to toggle the display of the <strong>TasksAdd</strong> component.
                            This also demonstrates conditional CSS styles based on state changes.
                        </p>
                        <p>
                            Within the context of this page the TasksAdd component loads the task information into the form and
                            then submits any changes to the Api.
                        </p>
                        <p>
                            Changing the reminder status also demonstrates conditional CSS on the task card component.
                        </p>
                        <p>
                            Finally the edit icon is provided by <strong>react-icons/fa</strong>
                        </p>
                        <hr />
                        <h3 className='h5 mt-4'>Bootstrap</h3>
                        <p>
                            This section is also generated by using the Card and Toast components provided by Bootstrap via CDN.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Task