name: "Azure React and Storybook Workflow"

on:
  push:
    branches:
      - components
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME_1: dev-react-demo-re01
  AZURE_WEBAPP_NAME_2: dev-react-demo-storybook-re01
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "14.x"

jobs:
  build_react_demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present       
          npm run test --if-present
        env:
          CI: false

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app-1
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app-1

      - name: "Deploy to dev-react-demo-re01"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_1 }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  build_storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: npm install, build-storybook
        run: |
          npm install
          npm run build-storybook
        env:
          CI: false

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app-2
          path: ./storybook-static

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production UI Testing"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app-2

      - name: "Deploy to dev-react-demo-storybook-re01"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_2 }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STORYBOOK }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}