name: "Sending Update Email Test"

on:
  workflow_dispatch:

env:
  SERVERLESS_URL: ${{ secrets.SERVERLESS_MAILER_ADDRESS }}
  TO: ${{ secrets.SERVERLESS_SEND_TO }}
          
jobs:
  serverless_email_confirmation:
    runs-on: ubuntu-latest

    steps:
      - name: Sending Update Email
        run: |
          curl --request GET \
          --url 'https://dev-nodejs-canc-dev-azure-heartbeat.azurewebsites.net/api/NotifySiteUpdatedMailer?subject=Update-Notification&to=romayne@gmail.com&sites=Hello-World&source=GitHub-Actions'
